package com.tabeebkServer.pojo;
// Generated May 10, 2015 10:16:11 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="graduationprojecttabeebakdb"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class Account  implements java.io.Serializable {


     private Integer accountId;
     private Accounttype accounttype;
     private String username;
     private String password;
     private String displayName;

    public Account() {
    }

    public Account(Accounttype accounttype, String username, String password, String displayName) {
       this.accounttype = accounttype;
       this.username = username;
       this.password = password;
       this.displayName = displayName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="account_id", unique=true, nullable=false)
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="accountType_id", nullable=false)
    public Accounttype getAccounttype() {
        return this.accounttype;
    }
    
    public void setAccounttype(Accounttype accounttype) {
        this.accounttype = accounttype;
    }

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="display_name", nullable=false, length=45)
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }




}


