package com.tabeebkServer.pojo;
// Generated May 2, 2015 11:08:35 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="graduationprojecttabeebakdb"
)
public class Area  implements java.io.Serializable {


     private Integer idarea;
     private City city;
     private String areaNameEn;
     private String areaNameAr;

    public Area() {
    }

	
    public Area(City city) {
        this.city = city;
    }
    public Area(City city, String areaNameEn, String areaNameAr) {
       this.city = city;
       this.areaNameEn = areaNameEn;
       this.areaNameAr = areaNameAr;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idarea", unique=true, nullable=false)
    public Integer getIdarea() {
        return this.idarea;
    }
    
    public void setIdarea(Integer idarea) {
        this.idarea = idarea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_id", nullable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="area_nameEn", length=45)
    public String getAreaNameEn() {
        return this.areaNameEn;
    }
    
    public void setAreaNameEn(String areaNameEn) {
        this.areaNameEn = areaNameEn;
    }

    
    @Column(name="area_nameAr", length=45)
    public String getAreaNameAr() {
        return this.areaNameAr;
    }
    
    public void setAreaNameAr(String areaNameAr) {
        this.areaNameAr = areaNameAr;
    }




}


