package com.tabeebkServer.pojo;
// Generated May 24, 2015 2:45:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name="doctor"
    ,catalog="graduationprojecttabeebakdb"
)
public class Doctor  implements java.io.Serializable {


     private Integer doctorId;
     private Doctorspeciality doctorspeciality;
     private Gender gender;
     private String doctorName;
     private String doctorNameAr;
     private String doctorDegree;
     private String doctorDegreeAr;
     private String doctorImagepath;
     private int deleted;
     private Set<DoctorClinc> doctorClincs = new HashSet<DoctorClinc>(0);

    public Doctor() {
    }

	
    public Doctor(int deleted) {
        this.deleted = deleted;
    }
    public Doctor(Doctorspeciality doctorspeciality, Gender gender, String doctorName, String doctorNameAr, String doctorDegree, String doctorDegreeAr, String doctorImagepath, int deleted, Set<DoctorClinc> doctorClincs) {
       this.doctorspeciality = doctorspeciality;
       this.gender = gender;
       this.doctorName = doctorName;
       this.doctorNameAr = doctorNameAr;
       this.doctorDegree = doctorDegree;
       this.doctorDegreeAr = doctorDegreeAr;
       this.doctorImagepath = doctorImagepath;
       this.deleted = deleted;
       this.doctorClincs = doctorClincs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="doctor_id", unique=true, nullable=false)
    public Integer getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctorSpeciality_id")
    public Doctorspeciality getDoctorspeciality() {
        return this.doctorspeciality;
    }
    
    public void setDoctorspeciality(Doctorspeciality doctorspeciality) {
        this.doctorspeciality = doctorspeciality;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gender_id")
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }

    
    @Column(name="doctor_name", length=45)
    public String getDoctorName() {
        return this.doctorName;
    }
    
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    
    @Column(name="doctor_name_ar", length=45)
    public String getDoctorNameAr() {
        return this.doctorNameAr;
    }
    
    public void setDoctorNameAr(String doctorNameAr) {
        this.doctorNameAr = doctorNameAr;
    }

    
    @Column(name="doctor_degree", length=45)
    public String getDoctorDegree() {
        return this.doctorDegree;
    }
    
    public void setDoctorDegree(String doctorDegree) {
        this.doctorDegree = doctorDegree;
    }

    
    @Column(name="doctor_degree_ar", length=45)
    public String getDoctorDegreeAr() {
        return this.doctorDegreeAr;
    }
    
    public void setDoctorDegreeAr(String doctorDegreeAr) {
        this.doctorDegreeAr = doctorDegreeAr;
    }

    
    @Column(name="doctor_imagepath", length=100)
    public String getDoctorImagepath() {
        return this.doctorImagepath;
    }
    
    public void setDoctorImagepath(String doctorImagepath) {
        this.doctorImagepath = doctorImagepath;
    }

    
    @Column(name="deleted", nullable=false)
    public int getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(int deleted) {
        this.deleted = deleted;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctor")
    public Set<DoctorClinc> getDoctorClincs() {
        return this.doctorClincs;
    }
    
    public void setDoctorClincs(Set<DoctorClinc> doctorClincs) {
        this.doctorClincs = doctorClincs;
    }




}


