package com.tabeebkServer.pojo;
// Generated May 24, 2015 9:40:13 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hospitalspeciality generated by hbm2java
 */
@Entity
@Table(name="hospitalspeciality"
    ,catalog="graduationprojecttabeebakdb"
)
public class Hospitalspeciality  implements java.io.Serializable {


     private Integer id;
     private Doctorspeciality doctorspeciality;
     private Hospital hospital;
     private Integer deleted;

    public Hospitalspeciality() {
    }

    public Hospitalspeciality(Doctorspeciality doctorspeciality, Hospital hospital, Integer deleted) {
       this.doctorspeciality = doctorspeciality;
       this.hospital = hospital;
       this.deleted = deleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="speciality_id")
    public Doctorspeciality getDoctorspeciality() {
        return this.doctorspeciality;
    }
    
    public void setDoctorspeciality(Doctorspeciality doctorspeciality) {
        this.doctorspeciality = doctorspeciality;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hospital_id")
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }

    
    @Column(name="deleted")
    public Integer getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }




}


