package com.tabeebkServer.pojo;
// Generated Jun 8, 2015 8:12:48 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Labspeciality generated by hbm2java
 */
@Entity
@Table(name="labspeciality"
    ,catalog="graduationprojecttabeebakdb"
)
public class Labspeciality  implements java.io.Serializable {


     private Integer id;
     private Lab lab;
     private Labspecialities labspecialities;
     private Integer deleted;

    public Labspeciality() {
    }

    public Labspeciality(Lab lab, Labspecialities labspecialities, Integer deleted) {
       this.lab = lab;
       this.labspecialities = labspecialities;
       this.deleted = deleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="labid")
    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="specialityid")
    public Labspecialities getLabspecialities() {
        return this.labspecialities;
    }
    
    public void setLabspecialities(Labspecialities labspecialities) {
        this.labspecialities = labspecialities;
    }

    
    @Column(name="deleted")
    public Integer getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }




}


