package com.tabeebkServer.pojo;
// Generated Apr 19, 2015 2:31:24 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Micuser generated by hbm2java
 */
@Entity
@Table(name="micuser"
    ,catalog="graduationprojecttabeebakdb"
)
public class Micuser  implements java.io.Serializable {


     private MicuserId id;
     private User user;
     private Mic mic;
     private Date joinDate;

    public Micuser() {
    }

    public Micuser(MicuserId id, User user, Mic mic, Date joinDate) {
       this.id = id;
       this.user = user;
       this.mic = mic;
       this.joinDate = joinDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="micId", column=@Column(name="mic_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public MicuserId getId() {
        return this.id;
    }
    
    public void setId(MicuserId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mic_id", nullable=false, insertable=false, updatable=false)
    public Mic getMic() {
        return this.mic;
    }
    
    public void setMic(Mic mic) {
        this.mic = mic;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="join_date", nullable=false, length=19)
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }




}


