package com.tabeebkServer.pojo;
// Generated May 15, 2015 3:04:27 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reservationpayment generated by hbm2java
 */
@Entity
@Table(name="reservationpayment"
    ,catalog="graduationprojecttabeebakdb"
)
public class Reservationpayment  implements java.io.Serializable {


     private Integer id;
     private String paymentEn;
     private String paymentAr;

    public Reservationpayment() {
    }

    public Reservationpayment(String paymentEn, String paymentAr) {
       this.paymentEn = paymentEn;
       this.paymentAr = paymentAr;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="payment_en", length=45)
    public String getPaymentEn() {
        return this.paymentEn;
    }
    
    public void setPaymentEn(String paymentEn) {
        this.paymentEn = paymentEn;
    }

    
    @Column(name="payment_ar", length=45)
    public String getPaymentAr() {
        return this.paymentAr;
    }
    
    public void setPaymentAr(String paymentAr) {
        this.paymentAr = paymentAr;
    }




}


