package com.tabeebkServer.pojo;
// Generated Jun 8, 2015 8:12:48 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reservationpayment generated by hbm2java
 */
@Entity
@Table(name="reservationpayment"
    ,catalog="graduationprojecttabeebakdb"
)
public class Reservationpayment  implements java.io.Serializable {


     private Integer id;
     private String paymentEn;
     private String paymentAr;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Reservationpayment() {
    }

    public Reservationpayment(String paymentEn, String paymentAr, Set<Reservation> reservations) {
       this.paymentEn = paymentEn;
       this.paymentAr = paymentAr;
       this.reservations = reservations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="payment_en", length=45)
    public String getPaymentEn() {
        return this.paymentEn;
    }
    
    public void setPaymentEn(String paymentEn) {
        this.paymentEn = paymentEn;
    }

    
    @Column(name="payment_ar", length=45)
    public String getPaymentAr() {
        return this.paymentAr;
    }
    
    public void setPaymentAr(String paymentAr) {
        this.paymentAr = paymentAr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="reservationpayment")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


