package com.tabeebkServer.pojo;
// Generated Jun 8, 2015 8:12:48 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
    ,catalog="graduationprojecttabeebakdb"
)
public class Reservation  implements java.io.Serializable {


     private Integer reservationId;
     private Reservationstatus reservationstatus;
     private Reservationpayment reservationpayment;
     private User user;
     private Schedule schedule;
     private Date reservationTime;
     private Integer positionSlot;

    public Reservation() {
    }

	
    public Reservation(User user, Schedule schedule, Date reservationTime) {
        this.user = user;
        this.schedule = schedule;
        this.reservationTime = reservationTime;
    }
    public Reservation(Reservationstatus reservationstatus, Reservationpayment reservationpayment, User user, Schedule schedule, Date reservationTime, Integer positionSlot) {
       this.reservationstatus = reservationstatus;
       this.reservationpayment = reservationpayment;
       this.user = user;
       this.schedule = schedule;
       this.reservationTime = reservationTime;
       this.positionSlot = positionSlot;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="reservation_id", unique=true, nullable=false)
    public Integer getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="reservation_status")
    public Reservationstatus getReservationstatus() {
        return this.reservationstatus;
    }
    
    public void setReservationstatus(Reservationstatus reservationstatus) {
        this.reservationstatus = reservationstatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_type")
    public Reservationpayment getReservationpayment() {
        return this.reservationpayment;
    }
    
    public void setReservationpayment(Reservationpayment reservationpayment) {
        this.reservationpayment = reservationpayment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="schedule_id", nullable=false)
    public Schedule getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(Schedule schedule) {
        this.schedule = schedule;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="reservation_time", nullable=false, length=8)
    public Date getReservationTime() {
        return this.reservationTime;
    }
    
    public void setReservationTime(Date reservationTime) {
        this.reservationTime = reservationTime;
    }

    
    @Column(name="position_slot")
    public Integer getPositionSlot() {
        return this.positionSlot;
    }
    
    public void setPositionSlot(Integer positionSlot) {
        this.positionSlot = positionSlot;
    }




}


