package com.tabeebkServer.pojo;
<<<<<<< HEAD
// Generated May 24, 2015 9:40:13 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
=======
// Generated May 23, 2015 9:23:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
>>>>>>> 6689aef6dda3c5207775e14ccd6ef12c7e2f185a

/**
 * Reservationstatus generated by hbm2java
 */
@Entity
@Table(name="reservationstatus"
    ,catalog="graduationprojecttabeebakdb"
)
public class Reservationstatus  implements java.io.Serializable {


     private Integer id;
     private String statusEng;
     private String statusAr;
<<<<<<< HEAD
=======
     private Set<Reservation> reservations = new HashSet<Reservation>(0);
>>>>>>> 6689aef6dda3c5207775e14ccd6ef12c7e2f185a

    public Reservationstatus() {
    }

<<<<<<< HEAD
    public Reservationstatus(String statusEng, String statusAr) {
       this.statusEng = statusEng;
       this.statusAr = statusAr;
=======
    public Reservationstatus(String statusEng, String statusAr, Set<Reservation> reservations) {
       this.statusEng = statusEng;
       this.statusAr = statusAr;
       this.reservations = reservations;
>>>>>>> 6689aef6dda3c5207775e14ccd6ef12c7e2f185a
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="status_eng", length=45)
    public String getStatusEng() {
        return this.statusEng;
    }
    
    public void setStatusEng(String statusEng) {
        this.statusEng = statusEng;
    }

    
    @Column(name="status_ar", length=45)
    public String getStatusAr() {
        return this.statusAr;
    }
    
    public void setStatusAr(String statusAr) {
        this.statusAr = statusAr;
    }

<<<<<<< HEAD
=======
@OneToMany(fetch=FetchType.LAZY, mappedBy="reservationstatus")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }

>>>>>>> 6689aef6dda3c5207775e14ccd6ef12c7e2f185a



}


